# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblClasses',
            fields=[
                ('id_classes', models.AutoField(primary_key=True, serialize=False)),
                ('class_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tblStudent',
            fields=[
                ('id_students', models.AutoField(primary_key=True, serialize=False)),
                ('name_first', models.CharField(max_length=200)),
                ('name_last', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.BooleanField()),
                ('id_foreign_classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_information_system.tblClasses')),
            ],
        ),
        migrations.CreateModel(
            name='tblUnits',
            fields=[
                ('id_units', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='tblclasses',
            name='id_foreign_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_information_system.tblUnits'),
        ),
    ]
