# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_information_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblunits',
            name='name_unit',
            field=models.CharField(default='NOT SET', max_length=200),
            preserve_default=False,
        ),
    ]
