# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_information_system', '0002_tblunits_name_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblclasses',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='tblstudent',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='tblunits',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.RemoveField(
            model_name='tblclasses',
            name='id_foreign_units',
        ),
        migrations.AddField(
            model_name='tblclasses',
            name='id_foreign_unit_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unit_1', to='Student_information_system.tblUnits', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='tblclasses',
            name='id_foreign_unit_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unit_2', to='Student_information_system.tblUnits', verbose_name='Unit 2'),
        ),
        migrations.AddField(
            model_name='tblclasses',
            name='id_foreign_unit_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unit_3', to='Student_information_system.tblUnits', verbose_name='Unit 3'),
        ),
        migrations.AlterField(
            model_name='tblclasses',
            name='class_code',
            field=models.CharField(max_length=50, verbose_name='Class Code'),
        ),
        migrations.AlterField(
            model_name='tblstudent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudent',
            name='gender',
            field=models.BooleanField(verbose_name='Is Male'),
        ),
        migrations.AlterField(
            model_name='tblstudent',
            name='id_foreign_classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_information_system.tblClasses', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='tblstudent',
            name='name_first',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='tblstudent',
            name='name_last',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='tblunits',
            name='description',
            field=models.TextField(default='None', max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tblunits',
            name='name_unit',
            field=models.CharField(max_length=200, verbose_name='Unit Name'),
        ),
    ]
