# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_information_system', '0003_auto_20160225_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblclasses',
            name='id_foreign_unit_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unit_1', to='Student_information_system.tblUnits', verbose_name='Unit 1'),
        ),
        migrations.AlterField(
            model_name='tblclasses',
            name='id_foreign_unit_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unit_2', to='Student_information_system.tblUnits', verbose_name='Unit 2'),
        ),
        migrations.AlterField(
            model_name='tblclasses',
            name='id_foreign_unit_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unit_3', to='Student_information_system.tblUnits', verbose_name='Unit 3'),
        ),
        migrations.AlterField(
            model_name='tblstudent',
            name='gender',
            field=models.NullBooleanField(verbose_name='Is Male'),
        ),
    ]
