# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_information_system', '0004_auto_20160225_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudent',
            name='post_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Post Code'),
        ),
        migrations.AddField(
            model_name='tblstudent',
            name='travel_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Travel Time'),
        ),
        migrations.AlterField(
            model_name='tblclasses',
            name='id_classes',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Class ID'),
        ),
        migrations.AlterField(
            model_name='tblstudent',
            name='id_students',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Student ID'),
        ),
    ]
